// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
)

type Endpoint struct {
	Url            sql.NullString
	ExpectedStatus sql.NullInt64
}
