// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import ()

type Check struct {
	EndpointID   int64
	Status       int64
	ResponseTime int64
	CreatedAt    int64
}

type Endpoint struct {
	ID             int64
	Url            string
	ExpectedStatus int64
	CreatedAt      int64
}
