// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package database

import (
	"context"
)

const endpointsList = `-- name: EndpointsList :many
select url, expected_status from endpoints
`

func (q *Queries) EndpointsList(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.QueryContext(ctx, endpointsList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(&i.Url, &i.ExpectedStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
