# fly.toml app configuration file generated for minwa on 2024-08-20T11:33:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minwa'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '8080'
  MAIL_FROM = 'hello@robinverton.de'
  MAIL_TO = 'hello@robinverton.de'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
